blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas & open discussion
    url: https://github.com/ookyet/web3-identity-seo/discussions
    about: Use Discussions > Ideas for open-ended brainstorming.
