#!/usr/bin/env bash

set -euo pipefail

EXPECTED_AUTHOR_NAME="${OOKYET_COMMIT_AUTHOR_NAME:-ookyet}"
EXPECTED_AUTHOR_EMAIL="${OOKYET_COMMIT_AUTHOR_EMAIL:-ookyet.mid@gmail.com}"

fail() {
  echo "commit-msg blocked: $*" >&2
  exit 1
}

check_ident_values() {
  local label="$1"
  local name="$2"
  local email="$3"

  if [[ "$name" != "$EXPECTED_AUTHOR_NAME" || "$email" != "$EXPECTED_AUTHOR_EMAIL" ]]; then
    fail "$label must be $EXPECTED_AUTHOR_NAME <$EXPECTED_AUTHOR_EMAIL>; current is $name <$email>"
  fi
}

check_git_ident() {
  local git_var="$1"
  local label="$2"
  local ident name email

  ident="$(git var "$git_var" 2>/dev/null || true)"
  if [[ -z "$ident" ]]; then
    fail "could not read $label identity via git var $git_var"
  fi

  name="${ident%% <*}"
  email="${ident#*<}"
  email="${email%%>*}"
  check_ident_values "$label" "$name" "$email"
}

contains_forbidden_lines() {
  local msg_file="$1"

  perl -ne '
    if (/^\s*(?:Made-with|Generated-by|AI-generated-by|Authored-by|Created-by|Written-by):/i) { $bad = 1; }
    if (/^\s*(?:Co-authored-by|Signed-off-by|Reviewed-by|Acked-by):/i) { $bad = 1; }
    if (/^\s*[^A-Za-z0-9#\n]*\s*(?:Generated with|Created with|Made with|Co-authored with)\b/i) { $bad = 1; }
    if (/^\s*[^A-Za-z0-9#\n]*\s*(?:This commit message was generated|This commit was generated|Generated by)\b/i) { $bad = 1; }
    END { exit($bad ? 0 : 1) }
  ' "$msg_file"
}

sanitize_message() {
  local msg_file="$1"
  local tmp_file

  tmp_file="$(mktemp)"

  # Strip tool/watermark trailers before Git records the message.
  perl -ne '
    next if /^\s*(?:Made-with|Generated-by|AI-generated-by|Authored-by|Created-by|Written-by):/i;
    next if /^\s*(?:Co-authored-by|Signed-off-by|Reviewed-by|Acked-by):/i;
    next if /^\s*[^A-Za-z0-9#\n]*\s*(?:Generated with|Created with|Made with|Co-authored with)\b/i;
    next if /^\s*[^A-Za-z0-9#\n]*\s*(?:This commit message was generated|This commit was generated|Generated by)\b/i;
    print;
  ' "$msg_file" > "$tmp_file"

  mv "$tmp_file" "$msg_file"
  perl -0pi -e 's/[ \t]+$//mg; s/\n{3,}/\n\n/g; s/\A\n+//; s/\s+\z/\n/' "$msg_file"
}

validate_message() {
  local msg_file="$1"
  local subject

  if ! sed '/^#/d' "$msg_file" | grep -Eq '[^[:space:]]'; then
    fail "commit message is empty after removing tool/watermark trailers"
  fi

  subject="$(sed '/^#/d' "$msg_file" | awk 'NF { print; exit }')"

  if [[ ${#subject} -gt 100 ]]; then
    fail "subject is too long (${#subject} > 100): $subject"
  fi

  if ! perl -ne '
    next if /^#/;
    if (/[^\x09\x0A\x0D\x20-\x7E]/) {
      print STDERR "non-ASCII text at line $.: $_";
      $bad = 1;
    }
    END { exit($bad ? 1 : 0) }
  ' "$msg_file"; then
    fail "commit message must be ASCII English"
  fi

  if contains_forbidden_lines "$msg_file"; then
    fail "tool/author trailer remained after sanitization"
  fi
}

check_commit() {
  local commit="$1"
  local author_name author_email committer_name committer_email
  local msg_file

  git rev-parse --verify "$commit^{commit}" >/dev/null 2>&1 || fail "could not read commit $commit"

  author_name="$(git log -1 --pretty=format:%an "$commit")"
  author_email="$(git log -1 --pretty=format:%ae "$commit")"
  committer_name="$(git log -1 --pretty=format:%cn "$commit")"
  committer_email="$(git log -1 --pretty=format:%ce "$commit")"

  check_ident_values "$commit author" "$author_name" "$author_email"
  check_ident_values "$commit committer" "$committer_name" "$committer_email"

  msg_file="$(mktemp)"
  git log -1 --pretty=format:%B "$commit" > "$msg_file"

  if contains_forbidden_lines "$msg_file"; then
    rm -f "$msg_file"
    fail "commit $commit message contains AI/tool watermark or extra author trailer"
  fi

  validate_message "$msg_file"
  rm -f "$msg_file"
}

check_range() {
  local base="$1"
  local head="$2"
  local rev_spec commits commit

  # New branches report an all-zero base SHA; fall back to validating only the tip.
  if [[ -z "$base" || "$base" =~ ^0+$ ]]; then
    rev_spec="$head"
  else
    rev_spec="$base..$head"
  fi

  commits="$(git rev-list "$rev_spec" 2>/dev/null || true)"
  if [[ -z "$commits" ]]; then
    echo "commit-msg: no commits to check in range ${base:-<none>}..$head" >&2
    return 0
  fi

  for commit in $commits; do
    check_commit "$commit"
  done
}

if [[ "${1:-}" == "--check-head" ]]; then
  check_commit HEAD
  exit 0
fi

if [[ "${1:-}" == "--check-range" ]]; then
  check_range "${2:-}" "${3:-HEAD}"
  exit 0
fi

MSG_FILE="${1:-}"

if [[ -z "$MSG_FILE" || ! -f "$MSG_FILE" ]]; then
  fail "missing commit message file"
fi

check_git_ident "GIT_AUTHOR_IDENT" "author"
check_git_ident "GIT_COMMITTER_IDENT" "committer"
sanitize_message "$MSG_FILE"
validate_message "$MSG_FILE"

exit 0
